apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-app
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: playground.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: playground-app
                port:
                  number: 8888
